# Generated by Django 5.2.4 on 2025-10-14 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('store', '0001_initial'), ('store', '0002_order_code'), ('store', '0003_alter_product_book'), ('store', '0004_product_book_type_alter_customer_user'), ('store', '0005_rename_book_type_product_product_type'), ('store', '0006_alter_product_book'), ('store', '0007_alter_product_product_type'), ('store', '0008_product_active'), ('store', '0009_cartitem_price'), ('store', '0010_alter_cartitem_cart'), ('store', '0011_order_checked_out_at'), ('store', '0012_remove_order_code_order_cart_alter_order_status'), ('store', '0013_alter_order_cart'), ('store', '0014_remove_cart_checked_out_cart_checked_out_at'), ('store', '0015_remove_order_cart_cart_order'), ('store', '0016_remove_cart_order_order_cart_delete_orderitem')]

    dependencies = [
        ('book', '0001_initial'),
        ('book', '0002_alter_book_genres_alter_genre_name'),
        ('book', '0003_remove_book_book_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('checked_out_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='book.book')),
                ('product_type', models.CharField(choices=[('physical', 'Físico'), ('digital', 'Digital')], default='physical', max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Em processamento'), ('success', 'Sucesso'), ('Error', 'Erro')], default='pending', max_length=10)),
                ('checked_out_at', models.DateTimeField(null=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.cart')),
            ],
        ),
    ]
