# Generated by Django 5.2.4 on 2025-08-05 01:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
