# Generated by Django 5.2.4 on 2025-09-12 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_genres_alter_genre_name'),
        ('store', '0002_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='book.book'),
        ),
    ]
