# Generated by Django 5.2.4 on 2025-09-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_book_type_alter_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='book_type',
            new_name='product_type',
        ),
    ]
