# Generated by Django 5.2.4 on 2025-09-16 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_book_type'),
        ('store', '0005_rename_book_type_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='book.book'),
        ),
    ]
