# Generated by Django 5.2.4 on 2025-09-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('physical', 'Físico'), ('digital', 'Digital')], default='physical', max_length=10),
        ),
    ]
