# Generated by Django 5.2.4 on 2025-10-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checked_out_at',
            field=models.DateTimeField(null=True),
        ),
    ]
