# Generated by Django 5.2.4 on 2025-10-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial_squashed_0016_remove_cart_order_order_cart_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_price_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
