# Generated by Django 5.2.4 on 2025-08-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('genre', models.CharField(choices=[('romance', 'Romance'), ('thriller', 'Terror'), ('sci-fi', 'Ficção Científica'), ('fantasy', 'Fantasia'), ('adventure', 'Aventura'), ('self-help', 'Autoajuda')], max_length=25)),
                ('language', models.CharField(blank=True, default='Português', max_length=50)),
                ('publish_date', models.DateField(blank=True)),
            ],
        ),
    ]
