# Generated by Django 5.2.4 on 2025-09-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_genres_alter_genre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_type',
        ),
    ]
